/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Public } from "../../decorators/public.decorator";
import { Mg } from "./Mg";
import { MgCountArgs } from "./MgCountArgs";
import { MgFindManyArgs } from "./MgFindManyArgs";
import { MgFindUniqueArgs } from "./MgFindUniqueArgs";
import { DeleteMgArgs } from "./DeleteMgArgs";
import { MgService } from "../mg.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Mg)
export class MgResolverBase {
  constructor(
    protected readonly service: MgService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Mg",
    action: "read",
    possession: "any",
  })
  async _mgsMeta(@graphql.Args() args: MgCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Mg])
  @nestAccessControl.UseRoles({
    resource: "Mg",
    action: "read",
    possession: "any",
  })
  async mgs(@graphql.Args() args: MgFindManyArgs): Promise<Mg[]> {
    return this.service.mgs(args);
  }

  @Public()
  @graphql.Query(() => Mg, { nullable: true })
  async mg(@graphql.Args() args: MgFindUniqueArgs): Promise<Mg | null> {
    const result = await this.service.mg(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Mg)
  @nestAccessControl.UseRoles({
    resource: "Mg",
    action: "delete",
    possession: "any",
  })
  async deleteMg(@graphql.Args() args: DeleteMgArgs): Promise<Mg | null> {
    try {
      return await this.service.deleteMg(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
