/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Mg as PrismaMg } from "@prisma/client";

export class MgServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MgCountArgs, "select">): Promise<number> {
    return this.prisma.mg.count(args);
  }

  async mgs(args: Prisma.MgFindManyArgs): Promise<PrismaMg[]> {
    return this.prisma.mg.findMany(args);
  }
  async mg(args: Prisma.MgFindUniqueArgs): Promise<PrismaMg | null> {
    return this.prisma.mg.findUnique(args);
  }
  async createMg(args: Prisma.MgCreateArgs): Promise<PrismaMg> {
    return this.prisma.mg.create(args);
  }
  async updateMg(args: Prisma.MgUpdateArgs): Promise<PrismaMg> {
    return this.prisma.mg.update(args);
  }
  async deleteMg(args: Prisma.MgDeleteArgs): Promise<PrismaMg> {
    return this.prisma.mg.delete(args);
  }
}
